#docker build -t pelatihan11 .
#docker images
#docker run --name pelatihan11 -p 8086:80 -d pelatihan11:latest
#docker start pelatihan11

#--Remove Container
#docker stop pelatihan11
#docker rm pelatihan11
#--Remove Image
#docker rmi pelatihan11

FROM php:8.2-cli

RUN apt-get update -y && apt-get install -y \
    libmcrypt-dev \
    libonig-dev \
    libxml2-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl

RUN docker-php-ext-configure gd \
    && docker-php-ext-install pdo mbstring pdo_mysql gd zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . /app

RUN composer install

EXPOSE 80
CMD php artisan serve --host=0.0.0.0 --port=80
